### ISSUE TITLE
Custom Resolutions Not Showing

### ISSUE THREAD

**Issue by ryen13** [andreacremaschi/Syphon-virtual-screen#24]
I installed the package for Mac OSX 10.7.5 and got everything working smoothly. I ran into the issue of needing a higher resolution so I followed all of the directions to add additional resolutions to the .kext file. During the deleting kext cache step, I noticed that I would get an "illegal" error though. I found online someone saying to run "sudo kextcache -e" to accomplish the same thing and it seemed to work in Terminal. 

Computer was rebooted, but I don't see the option of the new resolutions I added in the SVS menu. Any ideas?

**Comment by andreacremaschi** [comment]
try to delete again the folder as super user:

```sudo rm -R /System/Library/Caches/com.apple.kext.caches/Startup/```

**Comment by ryen13** [comment]
Ah that was it! Thank you very much for all the help and quick responses.

**Comment by andreacremaschi** [comment]
You're welcome!
