### ISSUE TITLE
App does not open in OS X 10.9.5

### ISSUE THREAD

**Issue by dpentecost** [andreacremaschi/Syphon-virtual-screen#25]
Just downloaded, installed, restarted. App will not open with double-click or right-click Open, although Syphon Recorder shows it as a source - "display - Syphon Virtual Screen" shows in its source dropdown. 

MBP Retina

**Comment by micrem73** [comment]
App isn't supposed to open a proper window at startup; you should see an icon in the right upper corner, that allow to select the resolution and stop the syphon server.

**Comment by dpentecost** [comment]
Got it. Thanks! Just checked it out - works well. (I was a little bleary last night when I tried it)
