### ISSUE TITLE
Artrage4

### ISSUE THREAD

**Issue by andreacremaschi** [andreacremaschi/Syphon-virtual-screen#29]
@maclaproject says: 

Hi Andrea,
Thank you very much for what you made available!!!
I discover your work on SVS as I was looking for a solution to pipe a video output of Artrage4 that can go full-screen but is not Syphon-enabled. The idea is to pipe a painting and send it into madmapper to paint in live. I want to use this technology to paint with children in hospital and paint on all the buiding. 
I send a mail to Artrage and doesn't have any intention to make it available. I don't have a lot of skills on programming yet but I'm looking to see if a solution is possible. I have a macbookpro with Yosemite 1010.2. I downloaded SVS 1.3. I see SVS in madmapper but when I pass full-screen in Artrage 4 nothing appears. Can you guide me on this? Maybe you are the angel that I'm looking for...

**Comment by andreacremaschi** [comment]
@maclaproject
hi, i don't know Artrage but maybe this project could be interesting for you: 

https://github.com/zakk4223/SyphonInject

Do you know it?

**Comment by maclaproject** [comment]
Thank you Andrea,
I did'nt knew it..but it's very interesting project. I tried directly but it does'nt work with Artrage. I was able to syphon other programmes but Artrage does'nt inject. Still looking for a option...
