### ISSUE TITLE
Performance FPS

### ISSUE THREAD

**Issue by arronmabrey** [andreacremaschi/Syphon-virtual-screen#30]
I'm curious, what I can expect possible FPS performance to be.
I'm running quicktime in full screen mode at a resolution of 375x667 and getting about 8 FPS, to the Syphon simple client. 

Is this expected FPS? Or do you believe there may be an issue?

Thanks,
-- Arron

**Comment by andreacremaschi** [comment]
Not at all, you should be close to 60fps. Not sure what's going on with you configuration.

**Comment by arronmabrey** [comment]
So if it's just static content, like the desktop or an empty chrome browser tab, I will get about 120fps. However once VLC or QuickTime are playing I get about 8fps. I also experimented with a css animation playing in chrome and that too got about 8fps.

My main goal is to capture image data from an ios device as quickly/low latency as possible to perform image analysis on the frame data at ~ 60fps.

Quicktime has the ability to stream the devices display feed through the lightning sync/charge cable, this is used by developers to record screencast type videos, but it doesn't allow access to the live feed. 

I have yet to find a solution to capture the feed pragmatically from quicktime or the feed itself.

The best I have done is to screen capture quicktime itself playing back the feed, this approach has worked well enough for getting my project started but I'm at the point where this strategy has introduced to much latency and vsync drift to continue.

I'm not particularly looking for a "fix" I'm more just giving an overview, perhaps you might have some good ideas. :-)

**Comment by andreacremaschi** [comment]
I never tried, but maybe you're able to hijack Quicktime's OpenGL frame buffer using this:

https://github.com/zakk4223/SyphonInject

If it doesn't work with QuickTime you can try installing AirServer and streaming from you iPhone with AirPlay.

Good luck!
