### ISSUE TITLE
Greade idea man!

### ISSUE THREAD

**Issue by PnP** [andreacremaschi/Syphon-virtual-screen#31]
Frist of all Thanks! I will use SVS for setup a webapp fullscreen browser and send it to a madmapper for the projection correcting. but my final resolution is 2560 x 800 (double WXGA), my question.. is there a chance to set up these res on settings? i would really appreciate this :) Thanks again!
javier

http://www.grupomanso.com.ar
https://vimeo.com/grupomanso

**Comment by andreacremaschi** [comment]
Sure, check the README and, if your work with Yosemite, this thread: https://github.com/andreacremaschi/Syphon-virtual-screen/issues/27
