### ISSUE TITLE
Syphon-virtual-screen jerking when running 

### ISSUE THREAD

**Issue by Vjtarang** [andreacremaschi/Syphon-virtual-screen#32]
Hi I am using Syphon-virtual-screen on my new Mac book pro running Yosemite ver 10.10.3. Every time i run it,it keeps jerking in fact the entire machine slows down the moment you capture a video in it. Please some 1 help me 

Thanks !!

**Comment by andreacremaschi** [comment]
Hi, what do you mean with "capture a video in it"?

**Comment by Vjtarang** [comment]
Hi what I mean is that in am using a software called cross by mix vibes. Every time I send the out put to Syphon-virtual-screen the entire machine starts to lag and slows down

**Comment by andreacremaschi** [comment]
Sorry to hear, have you tried with [SyphonInject](https://github.com/zakk4223/SyphonInject)?

**Comment by Vjtarang** [comment]
What does this do??

**Comment by andreacremaschi** [comment]
Check the README

**Comment by Vjtarang** [comment]
well i tried it but it did not work !

**Comment by andreacremaschi** [comment]
I am sorry I don't know how to help you!

**Comment by Vjtarang** [comment]
Can i have you email id and i can send you a video of what exactly is hapenning and my be u can try and see what the problem is ??

**Comment by andreacremaschi** [comment]
ok, just please send me a link on dropbox, vimeo or similar

**Comment by Vjtarang** [comment]
ok super thanks

**Comment by Vjtarang** [comment]
here you go 
https://www.dropbox.com/s/6v1ptxbz6gscvne/ScreenFlow.mp4?dl=0

**Comment by Vjtarang** [comment]
https://vimeo.com/131770181

**Comment by andreacremaschi** [comment]
ugh. no idea what's going on here. 
have you tried with different software? i.e. syphon recorder+vdmx? 
on a different machine with the same software?
